config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :accounts
  namespace :backstage do
    resources :pages
    resources :sites, only: [:index, :show]

  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    
    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end
  mount Maglev::Engine => '/maglev'
  # get '(*path)', to: 'maglev/page_preview#index', defaults: { path: 'index' }, constraints: Maglev::PreviewConstraint.new

  resources :backstage, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'home#index'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/backstage.rb
module Backstage
  def self.table_name_prefix
    "backstage_"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_tenant :account
  
  validates :title, presence: true
  
  has_rich_text :content

  has_one_attached :cover_photo

  def thumbnail_url
    return nil unless cover_photo.attached?
    Rails.application.routes.url_helpers.rails_blob_url(cover_photo, disposition: 'attachment')
  end
  
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :account


end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_person_name
  has_noticed_notifications

  has_many :notifications, as: :recipient, dependent: :destroy
  has_many :services

  has_many :pages, class_name: 'Backstage::Page'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :subdomain, :domain)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show ]

  # GET /posts/1 or /posts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/helpers/backstage_helper.rb
module BackstageHelper
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-primary"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/shared/_footer.html.erb
<footer class="bg-light footer mt-auto py-3">
  <div class="container d-flex justify-content-between mx-auto text-muted">
    <span>&copy; <%= Date.today.year %> Your Company</span>
    <ul class="d-inline float-end list-inline mb-0">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<!-- maglev styles -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

<!-- vite -->
<%= vite_stylesheet_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= vite_client_tag %>
<%= vite_javascript_tag 'application' %>
 

app/views/shared/_navbar.html.erb
<% if current_user != true_user %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to stop_impersonating_madmin_impersonates_path, method: :post do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="container mt-4 mx-auto">
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/theme/sections/blog/highlighted_post.html.erb
<%#= maglev_section.wrapper_tag.div class: 'py-6 md:py-12 px-4 md:px-6' do %>
  <!-- <div class="container mx-auto"> -->
    <!-- <div class="mb-4">
      <h2 class="text-2xl font-bold">highlighted_post</h2>
      <p class="mt-1 text-sm text-gray-500">
        Generated by the <strong class="text-black">Maglev</strong> generator.
      </p>
    </div> -->

    <!-- Section settings -->
    <!-- <div class="border-t border-gray-200 px-0 md:px-10 py-5">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-x-4 gap-y-8">
        <div class="col-span-1">
          <h4 class="text-sm font-medium text-gray-500">
            Title
          </h4>
          <div class="mt-1 text-sm text-gray-900">
            <%#= maglev_section.setting_tag :title %>
          </div>
        </div>
        <div class="col-span-1">
          <h4 class="text-sm font-medium text-gray-500">
            Post
          </h4>
          <div class="mt-1 text-sm text-gray-900">
            <%#= maglev_section.setting_tag :post %>
          </div>
        </div>
      </div>
    </div> -->
    
  <!-- </div> -->
<%# end %>

<%= maglev_section.wrapper_tag.div class: 'py-6 md:py-12 px-6 md:px-0' do %>
  <% post = maglev_section.settings.post.item %>
  
  <div class="w-full md:max-w-4xl mx-auto space-y-8">
    <h2 class="uppercase font-bold text-xl">
      <%= maglev_section.setting_tag :title %>
    </h2>

    <%= link_to main_app.post_path(post), class: 'block' do %>
      <article class="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-10">
        <div class="bg-gray-100 w-full md:w-72 md:min-w-[theme(spacing.72)] rounded-lg bg-transparent overflow-hidden relative">
          <%= image_tag main_app.url_for(post.cover_photo), class: 'object-cover' %>
        </div>
        <div class="space-y-4">
          <header class="space-y-1">
            <p class="text-gray-400 text-xs uppercase"><%= l post.created_at.to_date, format: :long %></p>
            <h2 class="text-gray-800 text-2xl font-semibold"><%= post.title %></h2>
          </header>
          <div class="text-sm text-gray-700 leading-6">
            <%= truncate(strip_tags(post.content.to_s), length: 140) %>
          </div>
        </div>
      </article>
    <% end if post %>
  </div>
<% end %>

app/views/theme/sections/blog/latest_posts.html.erb
<%#= maglev_section.wrapper_tag.div class: 'py-6 md:py-12 px-4 md:px-6' do %>
  <!-- <div class="container mx-auto"> -->
    <!-- <div class="mb-4">
      <h2 class="text-2xl font-bold">latest_posts</h2>
      <p class="mt-1 text-sm text-gray-500">
        Generated by the <strong class="text-black">Maglev</strong> generator.
      </p>
    </div> -->

    <!-- Section settings -->
    <!-- <div class="border-t border-gray-200 px-0 md:px-10 py-5">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-x-4 gap-y-8">
        <div class="col-span-1">
          <h4 class="text-sm font-medium text-gray-500">
            Number of posts
          </h4>
          <div class="mt-1 text-sm text-gray-900">
            <%#= maglev_section.setting_tag :number_of_posts %>
          </div>
        </div>
        <div class="col-span-1">
          <h4 class="text-sm font-medium text-gray-500">
            More link
          </h4>
          <div class="mt-1 text-sm text-gray-900">
            <%#= maglev_section.setting_tag :more_link %>
          </div>
        </div>
      </div>
    </div> -->
    
  <!-- </div> -->
<%# end %>

<%= maglev_section.wrapper_tag.div class: 'py-3 md:py-6 px-6 md:px-0' do %>
  <div class="w-full md:max-w-4xl mx-auto">
    <div class="grid grid-cols-2 gap-8 border-y py-8 border-gray-200">
      <% Post.order(:created_at).limit(maglev_section.settings.number_of_posts.value.to_i).each do |post| %>
        <%= link_to main_app.post_path(post), class: 'block group' do %>
          <article class="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-10">
            <div class="bg-gray-100 w-full md:w-32 md:min-w-[theme(spacing.32)] rounded-lg bg-transparent overflow-hidden relative">
              <%= image_tag main_app.url_for(post.cover_photo), class: 'object-cover' %>
            </div>
            <header class="space-y-1">
              <p class="text-gray-400 text-xs uppercase"><%= l post.created_at.to_date, format: :long %></p>
              <h2 class="text-gray-800 text-xl font-semibold group-hover:text-gray-600"><%= post.title %></h2>
            </header>
          </article>
        <% end %>
      <% end %>
    </div>
    <div class="flex justify-end mt-4">
      <div class="group hover:text-gray-600">
        <%= maglev_section.setting_tag :more_link %>
        &nbsp;→
      </div>
    </div>
  </div>
<% end %>

app/views/theme/sections/feature/feature_01.html.erb
<%= maglev_section.wrapper_tag.div class: 'text-white bg-gray-900' do %>
  <div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="max-w-xl">
      <%= maglev_section.setting_tag :title, html_tag: 'h2', class: 'text-3xl font-bold sm:text-4xl' %>
      
      <%= maglev_section.setting_tag :body, html_tag: 'p', class: 'mt-4 text-gray-300' %>
    </div>

    <div
      class="grid grid-cols-1 gap-8 mt-8 md:gap-12 md:mt-16 md:grid-cols-2 lg:grid-cols-3"
    >
      <% maglev_section.blocks.each do |maglev_block| %>
        <%= maglev_block.wrapper_tag.div class: 'flex items-start' do %>
          <span class="flex-shrink-0 h-12 w-12 flex items-center justify-center bg-gray-800 rounded-lg">
            <%= maglev_block.setting_tag :icon, class: 'text-xl' %>
          </span>

          <div class="ml-4">
            <%= maglev_block.setting_tag :name, html_tag: 'h3', class: 'text-lg font-bold' %>
            
            <%= maglev_block.setting_tag :description, html_tag: 'p', class: 'mt-1 text-sm text-gray-300' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/theme/sections/feature/feature_02.html.erb
<%= maglev_section.wrapper_tag.section do %>
  <div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div
      class="grid grid-cols-1 lg:grid-cols-2 gap-y-8 lg:gap-x-16 lg:items-center"
    >
      <div class="max-w-lg mx-auto text-center lg:text-left lg:mx-0">
        <%= maglev_section.setting_tag :title, html_tag: 'h2', class: 'text-3xl font-bold sm:text-4xl' %>

        <%= maglev_section.setting_tag :body, html_tag: 'p', class: 'mt-4 text-gray-600' %>
        
        <%= maglev_section.setting_tag :button, class: 'inline-flex items-center px-8 py-3 mt-8 text-white bg-indigo-600 border border-indigo-600 rounded hover:bg-transparent hover:text-indigo-600 active:text-indigo-500 focus:outline-none focus:ring text-sm font-medium' %>
      </div>

      <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <% maglev_section.blocks.each do |maglev_block| %>
          <%= maglev_block.wrapper_tag.a class: 'block p-4 border border-gray-100 shadow-sm rounded-xl focus:outline-none focus:ring hover:border-gray-200 hover:ring-1 hover:ring-gray-200', href: maglev_block.settings.link.href do %>
            <span class="inline-block h-12 w-12 flex items-center justify-center rounded-lg bg-gray-50">
              <%= maglev_block.setting_tag :icon, class: 'text-xl' %>
            </span>

            <%= maglev_block.setting_tag :name, html_tag: 'h6', class: 'mt-2 font-bold' %>
            
            <%= maglev_block.setting_tag :description, html_tag: 'p', class: 'hidden sm:mt-1 sm:text-sm sm:text-gray-600 sm:block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/theme/sections/feature/feature_03.html.erb
<%= maglev_section.wrapper_tag.section class: 'text-white bg-gray-900' do %>
  <div class="max-w-screen-xl px-4 py-16 mx-auto sm:px-6 lg:px-8">
    <div class="max-w-lg mx-auto text-center">
      <%= maglev_section.setting_tag :title, html_tag: 'h2', class: 'text-3xl font-bold sm:text-4xl' %>

      <%= maglev_section.setting_tag :body, html_tag: 'p', class: 'mt-4 text-gray-300' %>      
    </div>

    <div class="grid grid-cols-1 gap-8 mt-8 md:grid-cols-2 lg:grid-cols-3">
      <% maglev_section.blocks.each do |maglev_block| %>
        <%= maglev_block.wrapper_tag.a class: 'block p-8 transition border border-gray-800 shadow-xl rounded-xl hover:shadow-pink-500/10 hover:border-pink-500/10' do %>
      
          <%= maglev_block.setting_tag :icon, class: 'text-3xl text-pink-500' %>

          <%= maglev_block.setting_tag :name, html_tag: 'h3', class: 'mt-4 text-xl font-bold text-white' %>

          <%= maglev_block.setting_tag :description, html_tag: 'p', class: 'mt-1 text-sm text-gray-300' %>
        <% end %>
      <% end %>
    </div>

    <div class="mt-12 text-center">
      <%= maglev_section.setting_tag :button, class: 'inline-flex items-center px-8 py-3 mt-8 text-white bg-pink-600 border border-pink-600 rounded hover:bg-transparent active:text-pink-500 focus:outline-none focus:ring text-sm font-medium' %>
    </div>
  </div>
<% end %>

app/views/theme/sections/review/_grades.html.erb
<% grade.times do %>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="w-5 h-5 text-yellow-400"
    viewBox="0 0 20 20"
    fill="currentColor"
  >
    <path
      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
    />
  </svg>
<% end %>

<% (5 - grade).times do %>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="w-5 h-5 text-gray-200"
    viewBox="0 0 20 20"
    fill="currentColor"
  >
    <path
      d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
    />
  </svg>
<% end %>

app/views/theme/sections/review/review_01.html.erb
<%= maglev_section.wrapper_tag.section do %>
  <div class="max-w-screen-xl px-4 py-8 mx-auto sm:px-6 lg:px-8">
    <%= maglev_section.setting_tag :title, html_tag: 'h2', class: 'text-xl font-bold sm:text-2xl' %>

    <div class="flex items-center mt-4">
      <%= maglev_section.setting_tag :grade, html_tag: 'p', class: 'text-3xl font-medium' %>
      
      <div class="ml-4">
        <div class="flex -ml-1">
          <%= render 'theme/sections/review/grades', grade: maglev_section.settings.grade.to_s.to_f.round %>
        </div>

        <p class="mt-0.5 text-xs text-gray-500">
          Based on <%= pluralize(maglev_section.settings.number_of_reviews, 'review') %>
        </p>
      </div>
    </div>

    <div class="grid grid-cols-1 mt-8 lg:grid-cols-2 gap-x-16 gap-y-12">
      <% maglev_section.blocks.each do |maglev_block| %>
        <%= maglev_block.wrapper_tag.blockquote do %>
          <header class="sm:items-center sm:flex">
            <div class="flex -ml-1">
              <%= render 'theme/sections/review/grades', grade: maglev_block.settings.grade.to_s.to_f.round %>
            </div>

            <%= maglev_block.setting_tag :highlight, html_tag: 'p', class: 'mt-2 font-medium sm:ml-4 sm:mt-0' %>
          </header>

          <%= maglev_block.setting_tag :testimonial, html_tag: 'p', class: 'mt-2 text-gray-700' %>
          
          <footer class="mt-4">
            <%= maglev_block.setting_tag :person, html_tag: 'p', class: 'text-xs text-gray-500' %>
          </footer>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/theme/sections/testimonial/testimonial_01.html.erb
<%= maglev_section.wrapper_tag.section do %>
  <div class="max-w-5xl px-4 py-8 mx-auto">
    <section class="p-8 bg-gray-100 rounded-lg">
      <div class="grid grid-cols-1 gap-12 sm:grid-cols-3 sm:items-center">
        <%= maglev_section.setting_tag :picture, class: "object-cover w-full rounded-lg aspect-square" %>
        
        <blockquote class="sm:col-span-2">
          <%= maglev_section.setting_tag :quote, html_tag: 'p', class: 'text-xl font-medium sm:text-2xl' %>
          
          <cite class="inline-flex items-center mt-8 not-italic">
            <span class="hidden w-6 h-px bg-gray-400 sm:inline-block"></span>
            <p class="text-sm text-gray-500 uppercase sm:ml-3">
              <%= maglev_section.setting_tag :fullname, html_tag: 'strong' %>,&nbsp;<%= maglev_section.setting_tag :position %>
            </p>
          </cite>
        </blockquote>
      </div>
    </section>
  </div>
<% end %>