config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :accounts
  namespace :backstage do
    resources :pages
    resources :sites, only: [:index, :show]

  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    
    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end
  mount Maglev::Engine => '/maglev'
  # get '(*path)', to: 'maglev/page_preview#index', defaults: { path: 'index' }, constraints: Maglev::PreviewConstraint.new

  resources :backstage, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'home#index'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
end

app/models/backstage.rb
module Backstage
  def self.table_name_prefix
    "backstage_"
  end
end

app/models/backstage/page.rb
class Backstage::Page < ApplicationRecord
    belongs_to :user

    extend FriendlyId
    friendly_id :slug_candidates, use: %i[slugged finders history]
  
    # Try building a slug based on the following fields in
    # increasing order of specificity.
    def slug_candidates
      [
        :title
      ]
    end
  
    def update_slug
      # self.slug = title.parameterize
    end
  
    def should_generate_new_friendly_id?
      title_changed?
    end
  
end

app/controllers/backstage/pages_controller.rb
class Backstage::PagesController < ApplicationController

  layout 'team_worker'
  before_action :set_page, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def home; end

  # GET /pages/1 or /pages/1.json
  # non-REST pattern
  def show
    @pages = current_user.pages
    @page = current_user.pages.friendly.find(params[:id])
  end

  # GET /pages or /pages.json
  def index
    @page = if current_user.pages.count > 0
              current_user.pages.first
            else
              current_user.pages.create!(user: current_user)
            end
    redirect_to @page
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(user: current_user, site: @current_site)
    # @page.update_slug
    # @page = Page.new(user: current_user, site: Site.first)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page)}
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    # User.create! name: "Joe Schmoe"
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page) }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Backstage::Page.friendly.find(params[:id])
  end



  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :body)
  end
end

app/controllers/backstage/sites_controller.rb
class Backstage::SitesController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/backstage_controller.rb
class BackstageController < ApplicationController
  def index
  end
end

app/helpers/backstage/pages_helper.rb
module Backstage::PagesHelper
end

app/helpers/backstage/sites_helper.rb
module Backstage::SitesHelper
end

app/helpers/backstage_helper.rb
module BackstageHelper
end

app/views/backstage/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :slug %>
    <%= f.input :body %>
    <%= f.association :user %>
    <%= f.input :position %>
    <%= f.association :parent %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/backstage/pages/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

<!-- vite -->
<%= vite_stylesheet_tag "application", media: "all", "data-turbo-track": "reload" %>
<%= vite_client_tag %>
<%= vite_javascript_tag 'application' %>
<!-- <style>

    body {
        color: orange;
    }
</style> -->

app/views/backstage/pages/_page.html.erb
<!-- <pre>logo below</pre>
<p>&nbsp;</p>
<%#= vite_image_tag '/images/logo.png' %>
<%#= vite_image_tag 'images/logo.png' %>

<pre>logo above</pre> -->

<!-- https://www.notion.so/Demo-of-basics-85111017dba645648c70ad5377a61739 -->
<div class="grid grid-cols-12 gap-1 relative">
  <%= render "sidebar", locals: {page: page} %>

  <main class="w-full md:col-start-3 col-span-10">
    <div class="sticky top-0 full-width">
      <%= render 'shared/navbar' %>
      <%= render 'shared/notices' %>
    </div>
    <div>
      <img class="block h-[30vh] w-full object-cover object-[center_50%]" src="https://images.unsplash.com/photo-1616757729729-c59374fc50fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMjIwNjR8MHwxfHJhbmRvbXx8fHx8fHx8fDE2NTA3NTcyNDc&ixlib=rb-1.2.1&q=80&w=1080" />
    </div>
    <div class="flex w-full justify-center">
      <div class="w-[900px]">
        <div class="group w-full cursor-pointer pl-[2rem] md:pl-[96px]">
          <div class="flex justify-start">
            <button class="mt-4 flex h-6 items-center rounded-sm px-2 text-sm text-gray-400 opacity-100 md:opacity-0 transition-colors hover:bg-gray-100 group-hover:opacity-100">
              <svg class="mr-1 h-4 w-4" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path fill="none" d="M0 0h24v24H0z" />
                <path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zM7 12a5 5 0 0 0 10 0h-2a3 3 0 0 1-6 0H7z" />
              </svg>
              Add icon
            </button>
            <button class="mt-4 flex h-6 items-center rounded-sm px-2 text-sm text-gray-400 opacity-100 md:opacity-0 transition-colors hover:bg-gray-100 group-hover:opacity-100">
              <svg class="mr-1 h-4 w-4" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clip-rule="evenodd" />
              </svg>
              Add cover
            </button>
          </div>

          <style>


            .editable:empty:before {
              content: attr(data-placeholder);
              color: #999;
            }
          </style>

          <div class="pr-[2rem] md:pr-[96px]">
            <%= form_with model: @page, data: {controller: "editable"} do |f| %>
            <!-- nb: no whitespace in the h1 below -->
            <h1 
            contenteditable 
            data-editable-target="content" 
            data-action="keyup->editable#changed" 
            data-placeholder= "Untitled"
            class="editable whitespace-pre-wrap break-words p-1 text-4xl font-bold text-gray-900"
            ><%= @page.title %></h1>
  
              <%= f.hidden_field :title, data: {editable_target: "input"} %>
            <% end %>
          </div>
        </div>
        <div class="w-full px-[2rem] md:px-[96px]">
          <div class="py-2 px-4">
            <div class="-mx-3 my-3 flex items-start space-x-2">
              <div class="mt-1">
                <img class="h-6 w-6 rounded-full object-cover" src="https://lh3.googleusercontent.com/a-/AOh14GgBaFOzbAEgc3_1kvhT_rorTjiSwnvtznAvdSZ0BvM=s100" />
              </div>
              <div class="text-sm">
                <div class="space-x-1">
                  <span class="font-semibold">Dr Nic Williams</span>
                  <span class="text-xs text-gray-300">1 hour ago</span>
                </div>
                <p>My comment</p>
              </div>
            </div>
            <div class="-mx-3 my-3 flex items-start space-x-2">
              <div class="mt-1">
                <img class="h-6 w-6 rounded-full object-cover" src="https://lh3.googleusercontent.com/a-/AOh14GgBaFOzbAEgc3_1kvhT_rorTjiSwnvtznAvdSZ0BvM=s100" />
              </div>
              <div class="text-sm">
                <div class="space-x-1">
                  <span class="font-semibold">Dr Nic Williams</span>
                  <span class="text-xs text-gray-300">1 hour ago</span>
                </div>
                <p>Another comment</p>
              </div>
            </div>
            <div class="group -mx-3 my-3 flex items-center">
              <div class="mt-1">
                <img class="h-6 w-6 rounded-full object-cover" src="https://lh3.googleusercontent.com/a-/AOh14GgBaFOzbAEgc3_1kvhT_rorTjiSwnvtznAvdSZ0BvM=s100" />
              </div>
              <div class="w-full">
                <input type="text" placeholder="Another comment" class="w-full outline-none p-2 text-sm transition-colors group-hover:bg-gray-100">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- body -->
    <div class="flex w-full justify-center pt-1">
      <div class="w-full md:w-[900px]">
        <div class="w-full px-[2rem] md:px-[96px] pb-[30vh]">
          <div class="text-slate-800 space-y-2">
            <p>This is a paragraph.</p>
            <!-- notion.so has this outside this DOM and positions via JS -->
            <div class="absolute top-[6px] -left-5 text-gray-400">
              <div>
                <svg class="absolute top-0 left-0 h-3 w-3" fill="currentColor" viewBox="0 0 10 10"><path d="M3,2 C2.44771525,2 2,1.55228475 2,1 C2,0.44771525 2.44771525,0 3,0 C3.55228475,0 4,0.44771525 4,1 C4,1.55228475 3.55228475,2 3,2 Z M3,6 C2.44771525,6 2,5.55228475 2,5 C2,4.44771525 2.44771525,4 3,4 C3.55228475,4 4,4.44771525 4,5 C4,5.55228475 3.55228475,6 3,6 Z M3,10 C2.44771525,10 2,9.55228475 2,9 C2,8.44771525 2.44771525,8 3,8 C3.55228475,8 4,8.44771525 4,9 C4,9.55228475 3.55228475,10 3,10 Z M7,2 C6.44771525,2 6,1.55228475 6,1 C6,0.44771525 6.44771525,0 7,0 C7.55228475,0 8,0.44771525 8,1 C8,1.55228475 7.55228475,2 7,2 Z M7,6 C6.44771525,6 6,5.55228475 6,5 C6,4.44771525 6.44771525,4 7,4 C7.55228475,4 8,4.44771525 8,5 C8,5.55228475 7.55228475,6 7,6 Z M7,10 C6.44771525,10 6,9.55228475 6,9 C6,8.44771525 6.44771525,8 7,8 C7.55228475,8 8,8.44771525 8,9 C8,9.55228475 7.55228475,10 7,10 Z"></path></svg>
              </div>
              <div class="">
                <svg class="absolute top-0 -left-4 h-3 w-3" fill="currentColor" viewBox="0 0 16 16"><path d="M7.977 14.963c.407 0 .747-.324.747-.723V8.72h5.362c.399 0 .74-.34.74-.747a.746.746 0 00-.74-.738H8.724V1.706c0-.398-.34-.722-.747-.722a.732.732 0 00-.739.722v5.529h-5.37a.746.746 0 00-.74.738c0 .407.341.747.74.747h5.37v5.52c0 .399.332.723.739.723z"></path></svg>
              </div>
            </div>
            <p>This another a paragraph.</p>
            <div class="text-gray-400 underline underline-offset-0"><a href="https://google.com">https://google.com</a></div>
            <div class="bg-rose-50 p-6 font-mono rounded-sm">
              <div><span class="text-blue-500">class</span> <span class="text-red-500">Animal</span></div>
              <div><span class="text-blue-500">end</span></div>
            </div>
            <p>😬</p>
            <ul class="list-disc list-inside pl-3 space-y-2">
              <li>item 1</li>
              <li>item 2</li>
            </ul>
            <ol class="list-decimal list-inside pl-3 space-y-2">
              <li>one</li>
              <li>two</li>
            </ol>
            <ul class="list-none list-inside space-y-2">
              <li class="flex items-center space-x-2">
                <svg class="h-5 w-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm1 2v14h14V5H5z"/></svg>
                <span>item 1</span>
              </li>
              <li class="flex items-center space-x-2">
                <svg class="h-5 w-5 text-sky-500" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm7.003 13l7.07-7.071-1.414-1.414-5.656 5.657-2.829-2.829-1.414 1.414L11.003 16z"/></svg>
                <span class="text-slate-400 font-lighter line-through">item 2</span>
              </li>
            </ul>
            <h1 class="font-bold text-3xl pt-4 pb-2">h1</h1>
            <p>Text below h1</p>
            <h2 class="font-semibold text-2xl pt-3 pb-1">h2</h2>
            <p>Text below h2</p>
            <h3 class="font-semibold text-xl pt-2 pb-1">h3</h3>
            <p>Text below h3</p>
            <blockquote class="border-l-4 border-slate-800 pl-4 py-1">yeah, I said that<br>cool eh</blockquote>
            <div class="text-rose-900 bg-rose-200 p-4 rounded-sm flex items-start space-x-4">
              <a>
                <span role="image" aria-label="💡" style="font-family: 'Apple Color Emoji', 'Segoe UI Emoji', NotoColorEmoji, 'Noto Color Emoji', 'Segoe UI Symbol', 'Android Emoji', EmojiSymbols; line-height: 1em; white-space: nowrap;">💡</span>
              </a>
              <span>Ooh this is cool<br>isn't it?<span>
            </div>
            <div>
             <img src="https://images.unsplash.com/photo-1449034446853-66c86144b0ad?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb">
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/backstage/pages/_sidebar.html.erb
  <div id="nav-sidebar" class="col-start-1 col-span-2 hidden md:block w-full bg-rose-100 text-sm font-semibold text-slate-700">
    <div class="sticky inset-y-0 left-0">
      <div class="flex h-screen flex-col items-start">
        <div class="flex w-full flex-col items-start">
          <button class="top group !justify-between !py-2">
            <div class="flex items-center justify-start space-x-2">
              <div class="shrink-0"><img class="inline-block h-6 w-6 rounded-md" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="Picture of me" /></div>
              <div class="shrink-1 flex flex-col items-start">
                <span class="truncate text-sm text-slate-900">Dr Nic's Notes</span>
                <span class="truncate text-xs text-rose-500">drnic@mocra.com</span>
              </div>
            </div>
            <div>
              <svg class="h-3 w-3 text-rose-500" fill="currentColor" viewBox="-1 -1 9 11" xmlns="http://www.w3.org/2000/svg">
                <path d="m3.5 0 .488-.57L3.5-.987l-.488.419L3.5 0Zm0 9-.488.57.488.418.488-.419L3.5 9ZM.488 3.57l3.5-3-.976-1.14-3.5 3 .976 1.14Zm2.524-3 3.5 3 .976-1.14-3.5-3L3.012.57Zm-3.5 6 3.5 3 .976-1.14-3.5-3-.976 1.14Zm4.476 3 3.5-3-.976-1.14-3.5 3 .976 1.14Z" />
              </svg>
            </div>
          </button>
          <button class="top">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
            <span>Quick Find</span>
          </button>
          <button class="top">
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>All Updates</span>
          </button>
          <button class="top">
            <svg class="h-4 w-4" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
              <path fill="none" d="M0 0h16v16H0z"/>
              <path d="M16 9V7l-2.259-.753a6.01 6.01 0 0 0-.441-1.066l1.066-2.131-1.416-1.416L10.819 2.7a6.324 6.324 0 0 0-1.066-.441L9 0H7l-.753 2.259a6.085 6.085 0 0 0-1.066.441L3.05 1.638 1.638 3.05l1.066 2.131a6.024 6.024 0 0 0-.445 1.066L0 7v2l2.259.753c.112.372.263.728.441 1.066L1.634 12.95l1.416 1.416L5.181 13.3c.338.178.694.328 1.066.441L7 16h2l.753-2.259a6.01 6.01 0 0 0 1.066-.441l2.131 1.066 1.416-1.416-1.066-2.131c.178-.337.328-.694.441-1.066L16 9zm-8 2a3.001 3.001 0 0 1 0-6 3.001 3.001 0 0 1 0 6z"/>
            </svg>
            <span>Settings & Members</span>
          </button>
        </div>
        <div class="w-full grow overflow-y-scroll pt-3">
          <div class="flex flex-col items-start">
            <!-- start here  -->
            <!-- https://www.youtube.com/watch?v=XWfyffFWbDI&t=220s 51:25r -->
            <% @pages.each do |site_page| %>
              <%= render "sidebar_page", site_page: site_page %>
            <% end %>
          </div>
        </div>
        <div class="flex w-full flex-col items-start border-t border-rose-300">
          <%#= button_to "Create", { action: "create" }, remote: false %>          
          <form method="post" action="/pages" class="bg-pink w-full" >
            <button class="bg-pink w-full hover:bg-rose-300 text-grey-darkest font-bold py-2 px-4 rounded inline-flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
              </svg>
              <span>New Page</span>
            </button>
  
          </form>
        </div>
      </div>
    </div>
  </div>

app/views/backstage/pages/_sidebar_page.html.erb
<div class="hover:bg-rose-300 flex-auto ">
    <%= button_to (site_page.title || "Untitled"), backstage_page_url(site_page), method: "get"%>

</div>

app/views/backstage/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/backstage/pages/home.html.erb
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<span>test</span>
<br>
<span>mong2o</span>
<p>cholesterol</p>

<%= content_tag(:div, "", id: "app") %>

app/views/backstage/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/backstage/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/backstage/pages/show.html.erb
<%= content_for :title, @page.title || "Untitled" %>
<%= turbo_stream_from @page %>

<p style="color: green"><%= notice %></p>

<%= render @page %>