config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :accounts
  namespace :backstage do
    resources :pages
    resources :sites, only: [:index, :show]

  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    
    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end
  mount Maglev::Engine => '/maglev'
  # get '(*path)', to: 'maglev/page_preview#index', defaults: { path: 'index' }, constraints: Maglev::PreviewConstraint.new

  resources :backstage, only: [:index]
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'home#index'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant :account


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>


  <div class="mb-3">
    <% if project.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', project, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if project.persisted? %>
      <%= link_to "Cancel", project, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", projects_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= project.account_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Projects</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_project_path, class: 'btn btn-primary' do %>
    Add New Project
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Account</th>
            
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <%= content_tag :tr, id: dom_id(project), class: dom_class(project) do %>
          
            <td><%= link_to project.name, project %></td>
          

                      <td><%= project.account %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    All Projects
  <% end %>
  <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show project</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @project.name %></dd>
  <dt>Account:</dt>
  <dd><%= @project.account %></dd>
</dl>